### ISSUE TITLE
Latest version of pymupdf4llm.to_markdown returns empty text for some PDFs.

### ISSUE THREAD

**Issue by bbfrog** [pymupdf/RAG#281]
The old version 0.0.16 works, while the latest version doesn't (pymupdf4llm.to_markdown return empty text). Below is an example PDF, Please help to check and fix. Thanks! 

[Compass-Pathways-to-announce-fourth-quarter-and-year-end-financial-results-on-February-27th-2025-2025.pdf](https://github.com/user-attachments/files/20615366/Compass-Pathways-to-announce-fourth-quarter-and-year-end-financial-results-on-February-27th-2025-2025.pdf)

**Comment by JorjMcKie** [comment]
MuPDF issue link https://bugs.ghostscript.com/show_bug.cgi?id=708584

**Comment by JorjMcKie** [comment]
The MuPDF team has identified the reason: the use of "Type 3" fonts inevitably leads to alpha=0.
We will introduce an indicator that allows to detect this and react accordingly.

**Comment by JorjMcKie** [comment]
I have adjusted PyMuPDF4LLM to never ignore text that was written with a Type 3 font. This will resolve this issue.
Contained in version 0.0.25.

**Comment by JorjMcKie** [comment]
Fixed in version 0.0.25.

**Comment by azhurb** [comment]
It seems that 0.0.25 doesn't fix the problem for all cases. I have a PDF that works fine with 0.0.17, but I get an empty string on 0.0.24 and 0.0.25. Unfortunately, I can't share the file here, but it has images in the header, and the output of `pdffonts` is
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Courier                              Type 1            WinAnsi          no  no  no      22  0
Courier-Bold                         Type 1            WinAnsi          no  no  no      23  0
```
I can open a new issue if it helps.
